<div class="container main">
    <?php
    $usertype = strtolower(USER::Get(USER::TYPE));
    Index::__IncludeSidebar($usertype . '-course');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <c class="left"><?php echo $COURSE_INFOS['name']; ?></c>
        <?php
        if (DATA::__GetIntent('ALLOW_POST')=='true') {
            $frmPost = new FORM('frmPost', 'post', '', '');
            echo '<textarea name="postMessage" class="form-textarea-fullwidth" rows="5" placeholder="Write your post..."></textarea>';
            UI::NewLine();
            UI::NewLine();
            UI::Divbox(array(
                'align' => 'right'
            ), 
                UI::Button('Submit', 'submit', 'btn btn-primary btn-small', null, null, false) .
                UI::Button('Cancel', 'button', 'btn btn-warning btn-small', 
                        UI::GetPageUrl(Index::__GetPage(), array(
                            'ALLOW_POST' => 'false'
                        )), false)
            );
            $frmPost->EndForm();
        } else {
            UI::Divbox(
                array('align' => 'right'),
                UI::Button('Post a message', 'button', 'btn btn-primary btn-small',
                    UI::GetPageUrl(Index::__GetPage(), array(
                        'ALLOW_POST' => 'true'
                    )), false)
            );
        }
        ?>
        <br>
        <br>
        <?php
        foreach($a_threads as $thread) {
            echo $thread . PHP_EOL;
        }

        ?>
    </div>
</div>