<div class="container main">
    <?php
    $usertype = strtolower(USER::Get(USER::TYPE));
    Index::__IncludeSidebar($usertype . '-course');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <c class="left"><?php echo $COURSE_INFOS['name']; ?></c>
        <?php
        if (DATA::__GetIntent('ALLOW_POST')=='true') {
            $frmPost = new FORM('frmPost', 'post', '', '');
            echo '<textarea name="postMessage" class="form-textarea-fullwidth" rows="5" placeholder="Write your post..."></textarea>';
            UI::NewLine();
            UI::NewLine();
            UI::Divbox(array(
                'align' => 'right'
            ), 
                UI::Button('Submit', 'submit', 'btn btn-primary btn-small', null, null, false) .
                UI::Button('Cancel', 'button', 'btn btn-warning btn-small', 
                        UI::GetPageUrl(Index::__GetPage(), array(
                            'ALLOW_POST' => 'false'
                        )), false)
            );
            $frmPost->EndForm();
        } else {
            UI::Divbox(
                array('align' => 'right'),
                UI::Button('Post a message', 'button', 'btn btn-primary btn-small',
                    UI::GetPageUrl(Index::__GetPage(), array(
                        'ALLOW_POST' => 'true'
                    )), false)
            );
        }
        ?>
        <br>
        <br>
        <?php
        foreach($a_threads as $thread) {
            echo $thread . PHP_EOL;
        }

        ?>
        <!--
        <div class="thread">
            <?php $msg = "Do you know the reason why we're?".PHP_EOL."Because we're here!";  ?>
            <div class="row">
                <div class="col-lg-7 col-md-7 col-sm-7 thread-author">
                    <a href="#"><img src="web+/site/img/user.png">&nbsp;<b>Allen Linatoc</b></a>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-5 thread-datetime">
                    3:70pm &centerdot; 14 September 2014
                </div>
            </div>
            <div class="thread-message container-fluid row">
                <?php
                echo nl2br($msg);
                ?>
            </div>
            <div class="thread-controls row">
                <input type="button" class="btn btn-primary btn-xs thread-button" value="Reply">
                <input type="button" class="btn btn-warning btn-xs thread-button" value="Edit">
                <input type="button" class="btn btn-danger btn-xs thread-button" value="Delete">
            </div>
        </div>
        -->
    </div>
</div>