<div class="container main">
    <div class="container-fluid main-placeholder">
        <div class="row">
            <c class="col-lg-5 col-md-5 col-sm-5 left">Viewing task</c>
            <div class="col-lg-7 col-md-7 col-sm-7" align="right">
                <?php
                $userType = USER::Get(USER::TYPE);
                UI::Button('Back to tasks', 'button', 'btn btn-warning btn-small'
                      , UI::GetPageUrl($userType=='INSTRUCTOR' ? 'instructor-courses-home-tasks':'student-mycourses-tasks'));
                ?>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-7">
                <h3><i>Task details</i></h3>
                <hr>
                <b>Title: </b><?php echo $TASK_INFOS['title']; ?><br>
                <b>Description:</b>
                <p align="left" style="padding:1% 3%;">
                    <?php echo nl2br($TASK_INFOS['message']); ?>
                </p>
                <?php
                    $dateObj = new DateTime($TASK_INFOS['deaddate']);
                    $datePosted = new DateTime($TASK_INFOS['postdate']);
                    $remark = null;
                    if (($dateObj->getTimestamp()-time()) > 0 ) {
                        $remark = '('.DATEMAN::makeAgo($dateObj->getTimestamp(), time(), true).' left)';
                    }
                    else {
                        $remark = UI::Button('Deadline reached', 'button', 'btn btn-danger btn-xs', null, false);
                    }
                ?>
                <b>Posted: </b><?php echo $datePosted->format('F j, Y'); ?><br>
                <b>Deadline: </b><?php echo $dateObj->format('F j, Y') .' ' . $remark; ?><br>
                <br>
                <br>
            </div>
            
            <div class="col-lg-5 col-md-5 col-sm-5">
                <h3><i>Attachments</i></h3>
                <hr>
                <ul style="list-style: circle;">
                    <?php
                    $ctr = 1;
                    foreach($TASK_ATTACHMENTS as $attachment) {
                        $path = $attachment['tokenvalue'];
                        $ext = pathinfo($path, PATHINFO_EXTENSION);
                        $downloads = intval($attachment['downcount']);
                        echo '<li>' . UI::HTML('a', array('href' => UI::GetPageUrl('user-taskattachment', ['TA_ID'=>$attachment['id']]))
                                        , 'Attachment '.($ctr).'</a> ('.strtoupper($ext).')', false)
                                . ($downloads>0 ? (' - Downloaded '.$downloads.'x'):'')
                           . '</li>';
                        $ctr++;
                    }
                    ?>
                </ul>
            </div>
        </div>
        <hr>
        <?php
            
        ?>
        <div class="row container-fluid">
            <div class="row">
                <c class="col-lg-6 col-md-6 col-sm-6 left">Submissions</c>
                <div class="col-lg-6 col-md-6 col-sm-6" align="right">
                    <?php
                    if ($userType=='STUDENT') {
                        // check if this user has submitted already
                        $sql = new DB();
                        $sql
                                ->Select()
                                ->From('taskentry')
                                ->Where('task_id='.$TASK_INFOS['id'].' '
                                        . 'AND student_id='.USER::Get(USER::ID));
                        $submissionInfo = $sql->Query();
                        
                        UI::Button('Submit an entry', 'button', 'btn btn-primary btn-small',
                                UI::GetPageUrl('student-mycourses-tasks-submit', array( 'TASK_ID' => $TASK_INFOS['id'] )));
                        
                    }
                    ?>
                </div>
            </div>
            <br>
            <?php
            // For un-checked submissions
            if (USER::Get(USER::TYPE)=='INSTRUCTOR') {
                UI::HTML('c', ['class'=>'tableheading mid'], 'Pending submissions');
                $report_Unchecked->renderReport();
            }
            else if (USER::Get(USER::TYPE)=='STUDENT') {
                if (count($submissionInfo) > 0) {
                    // If there's a submission, show details
                    $submissionInfo = $submissionInfo[0];
                    echo '<p style="padding:3% 5%">';
                        echo '<b>You have submitted last</b> '.$submissionInfo['datetime'].' ';
                        UI::Button('Download the file', 'button', 'btn btn-primary btn-sm btn-marginized',
                                UI::GetPageUrl('user-taskattachment', ['TE_ID'=>$submissionInfo['id']]));
                        if ($submissionInfo['is_accepted']!=1) {
                            UI::Button('Cancel submission', 'button', 'btn btn-danger btn-sm btn-marginized', 
                                    UI::GetPageUrl(Index::__GetPage(), [
                                        'MODE' => 'REQ_CANCEL_TE',
                                        'TARGET_ID' => $submissionInfo['id']
                                    ]));
                        }
                        // show delete button
                        UI::Button('Delete submission', 'button', 'btn btn-danger btn-sm btn-marginized'
                                , UI::GetPageUrl(Index::__GetPage()
                                        , array(
                                            'MODE' => 'REQ_DELETE_SUBMISSION',
                                            'TE_ID' => $submissionInfo['id']
                                        )));
                        UI::NewLine(2);
                        echo '<b>Status: </b>'.($submissionInfo['is_accepted']==1 ? 'Accepted/Checked':'Pending');
                    echo '</p>';
                }
                else {
                    echo '<p style="padding: 3% 5%">You haven\'t submitted yet in this course.</p>';
                }
            }
            ?>
        </div>
        <hr>
        <div class="row container-fluid">
            <c class="tableheading mid">Checked submissions</c>
            <?php
            // For un-checked submissions
            
            $report_Checked->renderReport();
            ?>
        </div>
    </div>
</div>