<script type="text/javascript" language="javascript">
    function addFileUpload() {
        $('#spanfileinputs').append('<input type="file" name="postFile[]" required="required">');
        return false;
    }
</script>

<div class="container main">
    <div class="container-fluid main-placeholder">
        <c class="left">New task</c>
            <?php
            $frmTasks = new FORM('frmTasks', 'post', '?page='.Index::__GetPage(), '', 'left', array(
                'enctype' => 'multipart/form-data'
            ));
            $frmTasks->AddInput('Task title', 'postTitle', 'text', 
                    array(
                        "size" => 40,
                        "maxlength" => 40,
                        "required" => 'yes'
                    ), 'REQUIRED', 'Max. of 40 characters', false, '', $postTitle);
            UI::HTML('span', array('id' => 'spanfileinputs'), 
                    // file inputs
                    '<input type="file" name="postFile[]" id="postFile" required="required">', 
                true); ?>
            <input type="button" class="btn btn-primary btn-sm btn-marginized" onclick="return addFileUpload();" value="Attach more files">
            <br>
            <br>
            <br>
            <?php
            $frmTasks->AddTextarea('Task description', 'postMessage', $postMessage
                    , array(
                        'required' => 'required',
                        'maxlength' => '1500',
                        'rows' => 10
                    ), 'REQUIRED', 'Max. of 1500 characters', true);
            UI::NewLine(2);
            $frmTasks->AddInput("Deadline", "postDeaddate", "text", array(
                    'required' => 'required',
                    'maxlength' => 10,
                    'id' => 'postdeaddate',
                    'readonly' => 'readonly'
                ), "REQUIRED", "Format should be: mm/dd/yyyy");
            UI::HorizontalLine();
            $frmTasks->RenderSubmitButton('Submit');
            $frmTasks->RenderCancelButton('Cancel', 'instructor-courses-home-tasks');
            UI::Button('Reset', 'button', 'btn btn-warning btn-sm', UI::GetPageUrl(Index::__GetPage()));
            $frmTasks->EndForm();
            ?>
    </div>
</div>

<script type="text/javascript" language="javascript">
    $('#postdeaddate').datepicker({
        numberOfMonths : 1,
        changeMonth : true,
        changeYear : true,
        yearRange : 'c-0:c+1'
    });
   
</script>