<div class="container main">
    <?php
    Index::__IncludeSidebar('instructor-course');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <c class="left">Grade posting</c>
        <div class="row-fluid">
            <?php
            // echo 'Gperiod is '.$postGperiod;
            $frmGperiod = new FORM('frmGperiod', 'post', '', '', 'left', array('id' => 'frmgperiod'));
            $frmGperiod->AddDropdownSimple('Grading period', 'postGperiod', $gperiods, array(
                'required' => 'true',
                'onchange' => 'changeGperiod();'
            ), '', $postGperiod);
            if (DATA::__HasPostData())
            {
                // display 'Reset' button when selection is changed
                UI::Button('Reset', 'button', 'btn btn-primary btn-small btn-marginized', UI::GetPageUrl(Index::__GetPage()));
            }
            $frmGperiod->EndForm();
            ?>
        </div>
        <!-- Button controls -->
        <div class="row-fluid" align="right">
            <?php
            // Report controls
            if ( count($report_Gradetable->Rowdata) > 0 )
            {
                UI::Button('&nbsp;&nbsp;Edit&nbsp;&nbsp;', 'button', 'btn btn-primary btn-small btn-marginized'
                        , UI::GetPageUrl(Index::__GetPage().'-form'
                                , array(
                                    'MODE' => 'REQ_EDIT',
                                    'DCG_ID' => $postGperiod
                                )));
                UI::Button('Delete record', 'button', 'btn btn-danger btn-small btn-marginized'
                        , UI::GetPageUrl(Index::__GetPage()
                                , array(
                                    'MODE' => 'REQ_DROPRECORD',
                                    'DCG_ID' => $postGperiod
                                )));
            }
            ?>
        </div>
        <br>
        <br>
        <div class="row-fluid">
            <?php
            // Report (Gradetable)
            $report_Gradetable->renderReport();
            ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    function changeGperiod() {
        document.getElementById('frmgperiod').submit();
    }
</script>