<div class="container main">
    <?php
    Index::__IncludeSidebar('instructor-course');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <c class="left">Grade posting</c>
        <div class="row-fluid">
            <?php
            // echo 'Gperiod is '.$postGperiod;
            $frmGperiod = new FORM('frmGperiod', 'post', '', '', 'left', array('id' => 'frmgperiod'));
            $frmGperiod->AddDropdownSimple('Grading period', 'postGperiod', $gperiods, array(
                'required' => 'true',
                'onchange' => 'changeGperiod();'
            ), '', $postGperiod);
            if (DATA::__HasPostData())
            {
                // display 'Reset' button when selection is changed
                UI::Button('Reset', 'button', 'btn btn-primary btn-small btn-marginized', UI::GetPageUrl(Index::__GetPage()));
            }
            $frmGperiod->EndForm();
            ?>
        </div>
        <div class="row-fluid">
            <?php
            $report_Gradetable->renderReport();
            ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    function changeGperiod() {
        document.getElementById('frmgperiod').submit();
    }
</script>