<script type="text/javascript" language="javascript">
    function addFileUpload() {
        $('#spanfileinputs').prepend('<input type="file" name="postFile[]">').end();
        return false;
    }
</script>

<div class="container main">
    <div class="container-fluid main-placeholder">
        <c class="left">New task</c>
            <?php
            $frmTasks = new FORM('frmTasks', 'post', '', '', 'left', array(
                'enctype' => 'multipart/enctype'
            ));
            $frmTasks->AddInput('Task title', 'postTitle', 'text', 
                    array(
                        "size" => 40,
                        "maxlength" => 40,
                        "required" => 'yes'
                    ), 'REQUIRED', 'Max. of 40 characters', false, '', $postTitle);
            UI::HTML('span', array('id' => 'spanfileinputs'), 
                    // file inputs
                    '<input type="file" name="postFile[]">', 
                true); ?>
            <input type="button" class="btn btn-primary btn-sm btn-marginized" onclick="return addFileUpload();">
            <?php
            $frmTasks->RenderSubmitButton('Submit');
            $frmTasks->RenderCancelButton('Cancel');
            $frmTasks->EndForm();
            ?>
    </div>
</div>