<div class="container main">
    <?php
    Index::__IncludeSidebar('instructor-course');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <c class="left">Tasks/Assignments</c>
        <div class="container-fluid row" align="right">
            <?php
            UI::Button('New task', 'button', 'btn btn-primary btn-small', 
                    UI::GetPageUrl('instructor-courses-home-tasks-form'));
            ?>
        </div>
        <br>
        <div class="container-fluid row">
            <?php
            $report_Tasks->renderReport();
            ?>
        </div>
    </div>
</div>