<div class="col-lg-3 col-md-3 col-sm-3 main-placeholder">
    <c class="left">Panel sections</c>
    <ul class="sys-sidebar">
        <!--<li><?php UI::makeNavigationLink('Dashboard home', UI::GetPageUrl('user-home'), 'user-home') ?></li>-->
        <li><?php UI::makeNavigationLink('Course management', UI::GetPageUrl('instructor-courses'), 'instructor-courses'); ?></li>
    </ul>
    <hr>
    <ul class="sys-sidebar">
        <li><?php UI::makeNavigationLink('My account', UI::GetPageUrl('user-myaccount'
                , array(
                    'USER_ID' => USER::Get(USER::ID)
                )), 'iamuser');
        ?></li>
        <li><?php UI::makeNavigationLink('Logout', UI::GetPageUrl('logout'), 'logout');
        ?></li>
    </ul>
</div>