<div class="container main">
    <div class="container-fluid main-placeholder">
        <c class="left">Forgot password</c>
        <br>
        <?php
        // [case 1] : "Lookup for username existence/validity"
        if ($mode == '1_USERNAME')
        {
            $frmFpUsername = new FORM('frmFpUsername', 'post', '', '');
            $frmFpUsername->AddText('<i>Enter below the username of your account</i>');
            $frmFpUsername->AddInput('Username', 'postUsername', 'text', array(
                'required' => 'yes',
                'maxlength' => 20,
                'size' => 25
            ), 'REQUIRED', null);
            $frmFpUsername->RenderSubmitButton('Submit');
            $frmFpUsername->RenderCancelButton('Cancel', Index::$DEFAULT_PAGE);
            $frmFpUsername->EndForm();
        } 
        // [case 2] : "Checking through security question"
        else if ($mode == '2_SECURITY_CHECK') {
            $frmFpSecuritycheck = new FORM('frmFpSecuritycheck', 'post', '', '');
            $sql = new DB();
            $sql    ->Select(array('secquestion', 'secanswer'))
                    ->From('user')
                    ->Where('username LIKE \'%' . DATA::__GetIntent('FP_USERNAME') . '%\'');
            $result_Secquestion = ACCOUNTS::Encryptor($sql->Query()[0]['secquestion'], 'DECRYPT');
            $result_Secanswer = ACCOUNTS::Encryptor($sql->Query()[0]['secanswer'], 'DECRYPT');
            $frmFpSecuritycheck->AddText('<b>Answer the security question:</b>');
            UI::HTML('p', array(
                'style' => 'padding: 10px;'
            ), '<i>' . $result_Secquestion . '</i>');
            $frmFpSecuritycheck->AddInput('Your answer', 'postSecurityAnswer', 'text', array(
                'required' => 'yes',
                'maxlength' => '90',
                'size' => '30'
            ), 'REQUIRED', null, false, '', $postSecurityAnswer);
            $frmFpSecuritycheck->EndForm();
        }
        // [case 3] : "User is welcomed to change/reset his password"
        else if ($mode=='3_PASSWORD_CHANGE_MODE') {
            $frmFpPasswordchange = new FORM('frmFpPasswordchange', 'post', '', '');
            $frmFpPasswordchange->AddText('<i>Reset your password by using the form below</i>');
            UI::NewLine();
            $frmFpPasswordchange->AddInput('Enter new password', 'postNewpassword', 'password', array(
                'required' => 'yes',
                'maxlength' => 30,
                'size' => 35
            ), 'REQUIRED', 'Max. of 30 characters');
            $frmFpPasswordchange->AddInput('Confirm new password', 'postNewpassword2', 'password', array(
                'required' => 'yes',
                'maxlength' => 30,
                'size' => 35
            ), 'REQUIRED', null);
            $frmFpPasswordchange->RenderSubmitButton('Submit');
            $frmFpPasswordchange->EndForm();
        }
        ?>
        
        <!-- [comment] Button controls area -->
        <hr>
        <div class="row">
            <?php
            DATA::openPassage(Index::__GetPage());
            if ($mode!='1_USERNAME') {
                UI::HTML('div', array(
                    'class' => 'container col-lg-2 col-md-2 col-sm-2'
                ), 
                    UI::Button('Reset', 'button', 'btn btn-block btn-warning btn-small', 
                        UI::GetPageUrl(Index::__GetPage(), array(
                            'REQUEST' => 'RESET')), 
                    false)
                );
                UI::HTML('div', array(
                    'class' => 'container col-lg-2 col-md-2 col-sm-2'
                ), 
                    UI::Button('Cancel', 'button', 'btn btn-block btn-primary btn-small', 
                        UI::GetPageUrl(Index::$DEFAULT_PAGE), false)
                );
            }
            ?>
        </div>
    </div>
</div>