<div class="container main">
    <?php
        Index::__IncludeSidebar('student');
    ?>
    <div class="col-lg-9 col-md-9 col-sm-9 main-placeholder">
        <a href="<?php echo UI::GetPageUrl('student-mycourses'); ?>">&#171; Back to My courses</a>
        <c class="left">Enroll to a new course</c>
        <?php
        if (DATA::__GetIntent('COURSE_INFOS', true)) {
            $COURSE_INFOS = DATA::__GetIntent('COURSE_INFOS');
            UI::Divbox(array(
                'class' => 'col-lg-6 col-md-6 col-sm-6',
                'align' => 'center'),
                    'Course code matched!<br>'
                  . '<p align="center"><h4>' . $COURSE_INFOS['name'] . '</h4></p>'
                  . '<br>'
                  . UI::Button('Enroll', 'button', 'btn btn-primary btn-small', 
                          UI::GetPageUrl(Index::__GetPage(), array(
                                'IS_ENROLL' => 'true'
                            )),
                          false)
                  . UI::Button('Cancel', 'button', 'btn btn-warning btn-small', 
                          UI::GetPageUrl('student-mycourses-enroll', array(
                                'CANCEL_COURSE' => 'true'
                            )), 
                          false));
        }
        ?>
        <div class="col-lg-6 col-md-6 col-sm-6">
        Enter the course code:<br>
        <?php
        $frmEnroll = new FORM('frmEnroll', 'post', '', '');
        $frmEnroll->AddInput(null, 'postCoursecode', 'text', array(
            'required' => 'yes',
            'maxlength' => '11',
            'autofocus' => 'yes'
        ), 'REQUIRED', null, true, '', $postCoursecode);
        $frmEnroll->RenderSubmitButton('Submit');
        $frmEnroll->RenderCancelButton('Cancel', 'student-mycourses');
        $frmEnroll->EndForm();
        ?>
        </div>
    </div>
</div>