<div class="col-lg-3 col-md-3 col-sm-3 main-placeholder">
    <c class="left">Panel sections</c>
    <ul style="margin:0px; padding:0px 10px;">
        <li><?php UI::makeNavigationLink('Dashboard home', UI::GetPageUrl('user-home'), 'user-home'); ?></li>
        <li><?php UI::makeNavigationLink('My courses', UI::GetPageUrl('student-mycourses'), 'student-mycourses'); ?></li>
    </ul>
    <hr>
    <ul style="margin:0px; padding:0px 10px;">
        <li><?php UI::makeNavigationLink('My account', UI::GetPageUrl('user-myaccount'
                , array(
                    'USER_ID' => USER::Get(USER::ID)
                )), 'user-myaccount'); ?></li>
        <li><?php UI::makeNavigationLink('Logout', UI::GetPageUrl('logout')); ?></li>
    </ul>
</div>