<div class="col-lg-3 col-md-3 col-sm-3 main-placeholder">
    <c class="left">Panel sections</c>
    <ul style="margin:0px; padding:0px 10px;">
        <li><?php UI::makeNavigationLink('Dashboard home', UI::GetPageUrl('user-home'), 'user-home'); ?></li>
        <li><?php UI::makeNavigationLink('My courses', UI::GetPageUrl('student-mycourses'), 'student-mycourses'); ?></li>
        <li><?php UI::makeNavigationLink('Attendance reports', UI::GetPageUrl('student-attendancereports'), 'student-attendancereports'); ?></li>
        <li><?php UI::makeNavigationLink('Tasks/Assignments', UI::GetPageUrl('student-tasks'), 'student-tasks'); ?></li>
        <li><?php UI::makeNavigationLink('Grade reports', UI::GetPageUrl('student-gradereports'), 'student-gradereports'); ?></li>
    </ul>
    <hr>
    <ul style="margin:0px; padding:0px 10px;">
        <li><?php UI::makeNavigationLink('My account', UI::GetPageUrl('student-myaccount'), 'student-myaccount'); ?></li>
        <li><?php UI::makeNavigationLink('Logout', UI::GetPageUrl('logout')); ?></li>
    </ul>
</div>